# This is a basic workflow to help you get started with Actions

name: Deploy to AWS

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup node.js environment
        uses: actions/setup-node@v2.1.2
        
      - name: Npm install & npm build
        run: |
          npm install
          npm run build
          
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
          SOURCE_DIR: 'dist'
          
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v1.3
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/*'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-west-2'
      # Runs a single command using the runners shell
      - name: Send noti to lark bot
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true,"enable_forward":false},"i18n_elements":{"en_us":[{"tag":"div","fields":[{"is_short":false,"text":{"tag":"lark_md","content":"**TITLE**"}},{"is_short":false,"text":{"tag":"lark_md","content":"Deploy FE-Areas staging"}}]},{"tag":"div","fields":[{"is_short":false,"text":{"tag":"lark_md","content":"**MESSAGE**"}},{"is_short":false,"text":{"tag":"lark_md","content":"Deploy FE-Areas success"}}]},{"tag":"div","fields":[{"is_short":true,"text":{"tag":"lark_md","content":"**SEVERITY**"}},{"is_short":true,"text":{"tag":"lark_md","content":"**SERVER**"}},{"is_short":true,"text":{"tag":"plain_text","content":"Success"}},{"is_short":true,"text":{"tag":"plain_text","content":"Staging"}}]}]}}}' ${{secrets.LARK_BOT}}
