# This is a basic workflow to help you get started with Actions

name: Noti pull request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Send noti to lark bot
        run: |
           curl -H "Content-Type: application/json" -X POST -d '{"msg_type":"interactive","card":{"config":{"wide_screen_mode":true},"elements":[{"fields":[{"is_short":true,"text":{"content":"** 🗳 \tSOURCE **\nFE-Areas","tag":"lark_md"}},{"is_short":true,"text":{"content":"** 📅 \tDATE**\n${{ github.event.repository.updated_at}}","tag":"lark_md"}},{"is_short":false,"text":{"content":"","tag":"lark_md"}},{"is_short":true,"text":{"content":"**👤 \tBY WHO**\n${{ github.event.pull_request.user.login }}","tag":"lark_md"}},{"is_short":true,"text":{"content":"**📍\tBRANCH**\n${{github.event.pull_request.head.ref}}","tag":"lark_md"}}],"tag":"div"},{"actions":[{"tag":"button","text":{"content":"View pull request","tag":"plain_text"},"type":"primary","url":"${{ github.event.pull_request._links.html.href }}"}],"tag":"action"}],"header":{"template":"green","title":{"content":"NEW PULL REQUEST","tag":"plain_text"}}}}'  ${{secrets.LARK_BOT}}     
